title: Guido Salimbeni
description: ML Researcher & Artist
theme: minima
plugins:
  - jekyll-feed

# Fix these lines:
baseurl: "/blog" # your site is served from /blog subdirectory
url: "https://www.guidosalimbeni.it" # include https:// and no trailing slash
