title: Guido Salimbeni
description: ML Researcher & Artist
theme: minima
plugins:
  - jekyll-feed

#
baseurl: ""
url: "https://www.guidosalimbeni.it" # include https:// and no trailing slash

google_analytics: G-6VF1KEHVPH
